name: gutenprint-printer-applications # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snaps for Gutenprint Printer driver packages. # 79 char long summary
description: |
  This snap aims to provide modular snaps for Gutenprint printer driver packages.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  run-server:
    command: bin/server
    daemon: simple
    environment:
     GS_LIB: "/snap/hplip-printer-application/current/usr/share/ghostscript/9.26/Resource/Init"
     PYTHONPATH: "/snap/hplip-printer-application/current/lib/python2.7/site-packages/"
    plugs: 
    -  network 
    -  network-bind
    -  avahi-control
    -  raw-usb
    -  home
    -  hardware-observe
  run-deviced:
    command: bin/deviced
    environment:
      PYTHONPATH: "/snap/hplip-printer-application/current/lib/python2.7/site-packages/"
  run-ippprint:
    command: bin/ippprint
    environment:
     GS_LIB: "/snap/hplip-printer-application/current/usr/share/ghostscript/9.26/Resource/Init"

  run-ippeveprinter:
    command: bin/ippeveprinter
    environment:
     GS_LIB: "/snap/printer-application/current/usr/share/ghostscript/9.26/Resource/Init"
    plugs: [network, network-bind, avahi-control, raw-usb]

parts:
  ippsample:
    plugin: autotools
    source: https://github.com/dheeraj135/ippsample.git
    #source: ./ippsample
    # organize:
    #   lib/libcups.a: lib/ippsample/libcups.a
    configflags:
      - --datarootdir=/usr/share/
    build-packages:
    - libcups2-dev
    - zlib1g
    - liblzma5
    organize: 
      lib/libcups.a : lib/cups/

  server:
    # See 'snapcraft plugins'
    plugin: autotools
    source: https://github.com/dheeraj135/Printer-Applications-Framework.git
    #source: ./Printer-Applications-Framework/
    source-type: git
    build-packages:
      - libcups2
      - libcups2-dev
      - perl
      - automake
      - autoconf
      - m4
      - libudev-dev
      - libavahi-client-dev
      - libavahi-common-dev
      - libavahi-common3
      - libavahi-client3
      - libgnutls28-dev

    stage-packages:
      - libcups2
      - libavahi-common3
      - libavahi-client3
      - udev

    override-build: |
      autoreconf
      snapcraftctl build

    after: [ippsample]
  
  cups-filters:
    plugin: dump
    source: ./temp
    stage-packages:
    - cups-filters
    - cups
    prime:
    - usr/lib/cups/filter/
    - usr/share/cups/mime/
    stage:
    - usr/lib/cups/filter/
    - usr/share/cups/mime/
    organize:
     /usr/lib/cups/filter/* : usr/lib/cups/filter/
     /usr/share/cups/mime/* : usr/share/cups/mime/

  libraries:
    plugin: dump
    source: ./temp
    prime:
    - .
    stage:
    - .
    stage-packages:
    - libqpdf21
    - libcupsfilters1
    - ghostscript

  gutenprint:
    plugin: autotools
    source: ./gutenprint-5.2.15.tar.bz2
    after: [server]
    configflags:
    - --enable-cups-1_2-enhancements
    - --with-modules=dlopen
    - --disable-static
    build-packages:
      - libcups2-dev
      - libusb-1.0-0-dev
    stage-packages:
      - libcups2
      - libusb-1.0-0