name: printer-applications # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.0.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Snaps for Printer driver packages. # 79 char long summary
description: |
  This snap aims to provide modular snaps for different printer driver packages.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  run-server:
    command: bin/server
  run-deviced:
    command: bin/deviced
  run-ippprint:
    command: bin/ippprint
  run-ippeveprinter:
    command: bin/ippeveprinter
    environment:
     GS_LIB: "/snap/printer-applications/current/usr/share/ghostscript/9.26/Resource/Init"

parts:
  server:
    # See 'snapcraft plugins'
    plugin: autotools
    source: ./Printer-Applications-Framework
    source-type: git
    build-packages:
      - libcups2
      - libcups2-dev
      - perl
      - automake
      - autoconf
      - m4
      - libudev-dev
      - libpthread-stubs0-dev
      - libavahi-client-dev
      - libavahi-common-dev
      - libavahi-common3
      - libavahi-client3
      - zlib1g-dev
      - libgnutls28-dev
      - libgss3
      - libgss-dev

    stage-packages:
      - libcups2
      - libavahi-common3
      - libavahi-client3
      - libgss3

    override-build: |
      autoreconf
      snapcraftctl build

    after: [ippsample]
  
  ippsample:
    plugin: autotools
    source: ./ippsample
    # organize:
    #   lib/libcups.a: lib/ippsample/libcups.a
    configflags:
      - --datarootdir=/usr/share/
    build-packages:
    -  libcups2-dev
  
  hplip:
    plugin: autotools
    source: ./hplip-3.19.6.tar.gz
    after: [server]
    configflags:
    - --disable-scan-build
    - --prefix=/
    - --enable-new-hpcups
    - --datadir=/usr/share/
    build-packages:
    - libcups2-dev
    - libcups2
    - python-dev
    - perl
    - automake
    - autoconf
    - m4
    - libusb-1.0-0-dev
    - libsnmp-dev
    build-environment:
    - "CUPS_DATADIR" : "/root/parts/ippsample/install/share/cups/"
    stage-packages:
      - python-dev
      - libcups2-dev
      - libsnmp30
      - libusb-1.0-0
    override-build: |
      snapcraftctl build
      cp /lib/libImageProcessor* $SNAPCRAFT_PART_INSTALL/lib/
      rm $SNAPCRAFT_PART_INSTALL/lib/libImageProcessor.so
      cd $SNAPCRAFT_PART_INSTALL/lib/ && ln -s libImageProcessor*.so libImageProcessor.so

  # copy:
  #   plugin: dump
  #   source: /lib/
  #   after: [hplip]
  #   prime:
  #     - lib/libImageProcessor*
  #   organize:
  #    /lib/libImageProcessor*: lib/

  cups-filters-filters:
    plugin: dump
    source: ./temp
    stage-packages:
    - cups-filters
    - cups
    prime:
    - usr/lib/cups/filter/
    stage:
    - usr/lib/cups/filter/
    organize:
     /usr/lib/cups/filter/* : usr/lib/cups/filter/
  
  cups-filters-mime:
    plugin: dump
    source: ./temp
    stage-packages:
    - cups-filters
    - cups
    prime:
    - usr/share/cups/mime/
    stage:
    - usr/share/cups/mime/
    organize:
     /usr/share/cups/mime/* : usr/share/cups/mime/

  libraries:
    plugin: dump
    source: ./temp
    prime:
    - .
    stage:
    - .
    stage-packages:
    - libqpdf21
    - libcupsfilters1
    - ghostscript
     